### ISSUE TITLE
Open List

### ISSUE THREAD

**Issue by NoiKioN** [NoiKioN/SharedLists#1]
**The user should be capable of...**
- [ ] Selecting a list to open
- [ ] Viewing a list's contents

**The application should be capable of...**
- [ ] Opening a single list
- [ ] Displaying its contents to the user
