### ISSUE TITLE
Show Lists

### ISSUE THREAD

**Issue by NoiKioN** [NoiKioN/SharedLists#5]
**The user should be capable of...**
- [ ] Viewing the available and existing lists

**The app should be capable of...**
- [ ] Loading the existing lists
- [ ] Displaying the exisiting lists to the user
